package top.lrshuai.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActicle<M extends BaseActicle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setTagId(java.lang.Long tagId) {
		set("tag_id", tagId);
		return (M)this;
	}
	
	public java.lang.Long getTagId() {
		return getLong("tag_id");
	}

	public M setCreateBy(java.lang.Long createBy) {
		set("create_by", createBy);
		return (M)this;
	}
	
	public java.lang.Long getCreateBy() {
		return getLong("create_by");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setModifyBy(java.lang.Long modifyBy) {
		set("modify_by", modifyBy);
		return (M)this;
	}
	
	public java.lang.Long getModifyBy() {
		return getLong("modify_by");
	}

	public M setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
		return (M)this;
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

}
