package top.lrshuai.jfinal.model;

import top.lrshuai.jfinal.model.base.BaseActicle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Acticle extends BaseActicle<Acticle> {
	public static final Acticle dao = new Acticle().dao();
}
