package top.lrshuai.jfinal.model;

import top.lrshuai.jfinal.model.base.BaseAdminUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUser extends BaseAdminUser<AdminUser> {
	public static final AdminUser dao = new AdminUser().dao();
}
